<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(IslandsTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Types.fs" />
    <Compile Include="IslandProps.fs" />
    <Compile Include="NoteStore.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BlazorIslands.Server\BlazorIslands.Server.fsproj" />
  </ItemGroup>

</Project>

