// Regenerates THIRD-PARTY-NOTICES.md from the exact versions vendored into the BlazorIslands package.
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const vendored = [
  ['preact', 'preact.mjs, preact-hooks.mjs, preact-jsx-runtime.mjs'],
  ['@preact/signals', 'signals.mjs'],
  ['@preact/signals-core', 'signals-core.mjs'],
  ['htm', 'htm.mjs, htm-preact.mjs'],
];
let out = `# Third-party notices

The \`BlazorIslands\` package ships unmodified ESM builds of the following packages in
\`staticwebassets/vendor/\` (served at \`_content/BlazorIslands/vendor/\`). Their licenses follow.

Generated by \`eng/notices.cjs\` from the versions in \`package-lock.json\`.
`;
for (const [name, files] of vendored) {
  const dir = path.join(root, 'node_modules', name);
  const pkg = JSON.parse(fs.readFileSync(path.join(dir, 'package.json'), 'utf8'));
  const license = fs.readFileSync(path.join(dir, 'LICENSE'), 'utf8').trim();
  out += `\n## ${name} ${pkg.version} (${pkg.license})\n\nFiles: ${files}. Source: ${pkg.repository?.url ?? pkg.homepage ?? 'https://www.npmjs.com/package/' + name}\n\n\`\`\`\n${license}\n\`\`\`\n`;
}
fs.writeFileSync(path.join(root, 'THIRD-PARTY-NOTICES.md'), out);
console.log('wrote THIRD-PARTY-NOTICES.md');
