namespace BlazorIslands

open System
open System.Collections
open System.Collections.Generic
open System.Reflection
open System.Text
open System.Text.Json
open System.Text.Json.Serialization

/// Options for TypeScriptGenerator.
[<Sealed; AllowNullLiteral>]
type TypeScriptOptions() =
    /// Header comment emitted at the top of the file.
    member val Header = "// <auto-generated> by BlazorIslands.Codegen. Do not edit. </auto-generated>" with get, set
    member val JsonSerializerOptions = IslandJson.Default with get, set

/// Turns .NET types into TypeScript declarations: an interface for every reachable class, record or struct,
/// and a string-literal union for every enum.
/// C# nullable reference annotations and F# option types become `| null`; everything else is required.
type TypeScriptGenerator(options: TypeScriptOptions) =
    let options = if isNull options then TypeScriptOptions() else options
    let nullability = NullabilityInfoContext()
    let declared = Dictionary<Type, string>()
    let pending = Queue<Type>()
    let out = StringBuilder()


    static let reserved =
        set [ "break"; "case"; "catch"; "class"; "const"; "continue"; "debugger"; "default"; "delete"; "do"; "else"; "enum"
              "export"; "extends"; "false"; "finally"; "for"; "function"; "if"; "import"; "in"; "instanceof"; "new"; "null"
              "return"; "super"; "switch"; "this"; "throw"; "true"; "try"; "typeof"; "var"; "void"; "while"; "with" ]

    let isGen (def: Type) (t: Type) = t.IsGenericType && (let g = t.GetGenericTypeDefinition() in g = def || g.FullName = def.FullName)

    let fsOption = typedefof<option<int>>
    let fsValueOption = typedefof<voption<int>>
    let fsList = typedefof<list<int>>
    let fsMap = typedefof<Map<string, int>>
    let fsSet = typedefof<Set<int>>

    let isFSharpUnion (t: Type) =
        t.GetCustomAttributes(true)
        |> Array.exists (fun a ->
            let at = a.GetType()
            at.FullName = "Microsoft.FSharp.Core.CompilationMappingAttribute"
            && (at.GetProperty("SourceConstructFlags").GetValue(a).ToString() = "SumType"))

    let rec tsName (t: Type) =
        let baseName =
            let n = if t.IsGenericType then t.Name.Substring(0, t.Name.IndexOf '`') else t.Name
            if t.IsNested && not (isNull t.DeclaringType) && not t.DeclaringType.IsAbstract then t.DeclaringType.Name + n else n
        baseName

    let propertyName (p: PropertyInfo) =
        match p.GetCustomAttribute<JsonPropertyNameAttribute>() with
        | null ->
            match options.JsonSerializerOptions.PropertyNamingPolicy with
            | null -> p.Name
            | policy -> policy.ConvertName p.Name
        | a -> a.Name

    let quoteKey (name: string) =
        let isIdent =
            name.Length > 0
            && (Char.IsLetter name[0] || name[0] = '_' || name[0] = '$')
            && name |> Seq.forall (fun c -> Char.IsLetterOrDigit c || c = '_' || c = '$')
        if isIdent then name else JsonSerializer.Serialize name

    let enumMember (t: Type) (f: FieldInfo) =
        match f.GetCustomAttribute<JsonStringEnumMemberNameAttribute>() with
        | null -> f.Name
        | a -> a.Name

    let elementOfEnumerable (t: Type) =
        if t.IsArray then Some (t.GetElementType())
        else
            t.GetInterfaces()
            |> Array.append (if t.IsInterface then [| t |] else [||])
            |> Array.tryPick (fun i -> if isGen typedefof<IEnumerable<int>> i then Some (i.GetGenericArguments()[0]) else None)

    let dictionaryTypes (t: Type) =
        t.GetInterfaces()
        |> Array.append (if t.IsInterface then [| t |] else [||])
        |> Array.tryPick (fun i ->
            if isGen typedefof<IDictionary<int, int>> i || isGen typedefof<IReadOnlyDictionary<int, int>> i then
                let a = i.GetGenericArguments() in Some (a[0], a[1])
            else None)

    /// TypeScript for a type reference. nullable means the reference itself may be null.
    member private this.Ref(t: Type, nullable: bool, nullInfo: NullabilityInfo) : string =
        let withNull s = if nullable then $"{s} | null" else s
        let argInfo i =
            if isNull nullInfo then null
            elif t.IsArray then nullInfo.ElementType
            elif i < nullInfo.GenericTypeArguments.Length then nullInfo.GenericTypeArguments[i]
            else null
        let argNullable (i: int) (arg: Type) =
            let info = argInfo i
            if arg.IsValueType then not (isNull (Nullable.GetUnderlyingType arg))
            elif isNull info then false
            else info.ReadState = NullabilityState.Nullable
        if t.IsGenericParameter then withNull t.Name
        else
        match Nullable.GetUnderlyingType t with
        | null ->
            if t = typeof<string> || t = typeof<char> || t = typeof<Guid> || t = typeof<DateTime> || t = typeof<DateTimeOffset>
               || t = typeof<DateOnly> || t = typeof<TimeOnly> || t = typeof<TimeSpan> || t = typeof<Uri> || t = typeof<Version>
               || t = typeof<byte[]> then withNull "string"
            elif t = typeof<bool> then withNull "boolean"
            elif t.IsPrimitive || t = typeof<decimal> || t = typeof<Half> || t = typeof<Int128> || t = typeof<UInt128> then withNull "number"
            elif t = typeof<obj> || t = typeof<JsonElement> || t = typeof<JsonDocument> || t.FullName = "System.Text.Json.Nodes.JsonNode" then "unknown"
            elif t = typeof<unit> || t = typeof<Void> then "void"
            elif isGen fsOption t || isGen fsValueOption t then
                let inner = t.GetGenericArguments()[0]
                $"{this.Ref(inner, false, argInfo 0)} | null"
            elif t.IsEnum then
                this.Enqueue t
                withNull (tsName t)
            elif isGen fsMap t then
                let a = t.GetGenericArguments()
                withNull $"Record<{this.KeyRef a[0]}, {this.Ref(a[1], argNullable 1 a[1], argInfo 1)}>"
            elif (dictionaryTypes t).IsSome then
                let k, v = (dictionaryTypes t).Value
                let vi = if t.IsGenericType && t.GetGenericArguments().Length = 2 then argInfo 1 else null
                let vn = if v.IsValueType then not (isNull (Nullable.GetUnderlyingType v)) else (not (isNull vi) && vi.ReadState = NullabilityState.Nullable)
                withNull $"Record<{this.KeyRef k}, {this.Ref(v, vn, vi)}>"
            elif isGen typedefof<IAsyncEnumerable<int>> t then
                let a = t.GetGenericArguments()[0]
                $"AsyncIterable<{this.Ref(a, argNullable 0 a, argInfo 0)}>"
            elif t <> typeof<string> && (elementOfEnumerable t).IsSome then
                let e = (elementOfEnumerable t).Value
                let ei = if t.IsArray || (t.IsGenericType && t.GetGenericArguments().Length = 1) then argInfo 0 else null
                // An unannotated type parameter (IReadOnlyList<T>) reports Nullable; only T? would be, and that is rare in DTOs.
                let en = if e.IsGenericParameter then false elif e.IsValueType then not (isNull (Nullable.GetUnderlyingType e)) else (not (isNull ei) && ei.ReadState = NullabilityState.Nullable)
                withNull $"{this.Wrap(this.Ref(e, en, ei))}[]"
            elif t.FullName.StartsWith("System.Tuple`", StringComparison.Ordinal) || t.FullName.StartsWith("System.ValueTuple`", StringComparison.Ordinal) then
                raise (NotSupportedException $"Tuple type '{t}' does not round-trip through System.Text.Json. Use a record instead.")
            elif isFSharpUnion t then
                raise (NotSupportedException $"F# union '{t.FullName}' is not supported by System.Text.Json. Use a record with an enum tag, or a class hierarchy with [JsonPolymorphic].")
            elif t.IsGenericType && not t.IsGenericTypeDefinition then
                let def = t.GetGenericTypeDefinition()
                this.Enqueue def
                let args =
                    t.GetGenericArguments()
                    |> Array.mapi (fun i a -> this.Ref(a, argNullable i a, argInfo i))
                    |> String.concat ", "
                withNull $"{tsName def}<{args}>"
            else
                this.Enqueue t
                withNull (tsName t)
        | inner -> $"{this.Ref(inner, false, null)} | null"

    member private _.Wrap(s: string) = if s.Contains " | " || s.Contains "=>" then $"({s})" else s

    member private this.KeyRef(k: Type) =
        if k = typeof<string> || k = typeof<Guid> then "string"
        elif k.IsEnum then this.Ref(k, false, null)
        elif k.IsPrimitive then "string"
        else raise (NotSupportedException $"Dictionary key type '{k}' cannot be a JSON object key.")

    member private _.Enqueue(t: Type) =
        if not (declared.ContainsKey t) then
            declared[t] <- tsName t
            pending.Enqueue t

    member private this.DeclareEnum(t: Type) =
        let members =
            t.GetFields(BindingFlags.Public ||| BindingFlags.Static)
            |> Array.map (fun f -> JsonSerializer.Serialize(enumMember t f))
        out.Append("export type " + tsName t + " = " + String.Join(" | ", members) + ";").Append('\n') |> ignore
        out.Append('\n') |> ignore

    member private this.DeclareObject(t: Type) =
        let generics =
            if t.IsGenericTypeDefinition then "<" + String.Join(", ", t.GetGenericArguments() |> Array.map (fun a -> a.Name)) + ">" else ""
        out.Append($"export interface {tsName t}{generics} {{").Append('\n') |> ignore
        let props =
            t.GetProperties(BindingFlags.Public ||| BindingFlags.Instance)
            |> Array.filter (fun p -> p.GetIndexParameters().Length = 0 && p.CanRead)
            |> Array.filter (fun p ->
                match p.GetCustomAttribute<JsonIgnoreAttribute>() with
                | null -> true
                | a -> a.Condition <> JsonIgnoreCondition.Always)
            |> Array.sortBy (fun p -> p.MetadataToken)
        for p in props do
            let info = try nullability.Create p with _ -> null
            let nullable =
                if p.PropertyType.IsValueType then not (isNull (Nullable.GetUnderlyingType p.PropertyType))
                elif p.PropertyType.IsGenericParameter then false
                elif isNull info then true
                else info.ReadState = NullabilityState.Nullable
            out.Append($"  {quoteKey (propertyName p)}: {this.Ref(p.PropertyType, nullable, info)};").Append('\n') |> ignore
        out.Append("}").Append('\n') |> ignore
        out.Append('\n') |> ignore

    member private this.Drain() =
        while pending.Count > 0 do
            let t = pending.Dequeue()
            if t.IsEnum then this.DeclareEnum t else this.DeclareObject t

    new() = TypeScriptGenerator(null)

    /// Generates a TypeScript module declaring every given type and everything it references.
    member this.Generate(types: Type seq) : string =
        out.Clear() |> ignore
        declared.Clear()
        pending.Clear()
        for t in types do
            this.Enqueue(if t.IsGenericType && not t.IsGenericTypeDefinition then t.GetGenericTypeDefinition() else t)
        this.Drain()
        let sb = StringBuilder()
        sb.Append(options.Header).Append('\n') |> ignore
        sb.Append("/* eslint-disable */").Append('\n') |> ignore
        sb.Append('\n') |> ignore
        sb.Append(out.ToString()) |> ignore
        sb.ToString().TrimEnd() + "\n"

    /// Generates for every [TypeScript] type in the assemblies.
    member this.GenerateFrom(assemblies: Assembly seq) : string =
        assemblies
        |> Seq.collect (fun a ->
            let types = try a.GetTypes() with :? ReflectionTypeLoadException as e -> e.Types |> Array.filter (isNull >> not)
            types |> Array.filter (fun t -> not (isNull (t.GetCustomAttribute<TypeScriptAttribute>()))))
        |> Seq.sortBy (fun t -> t.FullName)
        |> this.Generate







